[versions]
compile-sdk = "36"
min-sdk = "24"
composeHotReload = "1.0.0-rc04"
kotlinx-coroutines = "1.10.2"
kotlinx-browser = "0.5.0"

[libraries]
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinx-browser" }

[plugins]
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
